-- Write a SQL statement to complete the following database query
-- Write a SQL query to return all the Projects for the User whose `id` is `1`
-- Check that it works by running `psql project_planner_development < db/queries.sql`
