---
title: "Capstone Project Deliverable #2 - User Stories, Acceptance Criteria, and ER Diagrams"
type: "challenge"
description: "Your initial pass at user stories, acceptance criteria, and ER diagrams for your capstone-project."
tags: "capstone-project"
ignore:
- "capstone-project-deliverable-2.md"
